/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 cj.gltf --transform
Author: Harlie/Kaeul (https://sketchfab.com/harleymh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cj-gtasa-535910c6ba5e4530b4eb48382474b72f
Title: CJ GTA:SA
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cj(props) {
  const { nodes, materials } = useGLTF('/cj-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <mesh geometry={nodes.CABEZA_Mat_0.geometry} material={materials.Mat_2} />
      <mesh geometry={nodes.TORSO_Mat_0.geometry} material={materials.Mat_1} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.material} skeleton={nodes.Object_6.skeleton} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Mat_0} skeleton={nodes.Object_8.skeleton} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Mat_1} skeleton={nodes.Object_10.skeleton} />
    </group>
  )
}

useGLTF.preload('/cj-transformed.glb')
