/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 head.gltf --transform
Author: matosm27 (https://sketchfab.com/matosm27)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grand-theft-auto-vice-city-lance-vance-6ffdec414396449f9c2f3bf61f7643a2
Title: Grand Theft Auto Vice City - Lance Vance
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Head (props) {
  const { nodes, materials } = useGLTF('/head-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Root.0']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/head-transformed.glb')
