/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 head.gltf --transform
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/head-of-michelangelos-david-optimised-d29af50360624e5e9b1855666475380d
Title: Head Of Michelangelo's David, Optimised
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HeadMiky(props) {
  const { nodes, materials } = useGLTF('/headMiky-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[7.061, -30.641, 175.622]} rotation={[3.129, -0.082, -0.011]} scale={0.003} />
    </group>
  )
}

useGLTF.preload('/headMiky-transformed.glb')
