/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 kenVice.gltf --transform
Author: matosm27 (https://sketchfab.com/matosm27)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grand-theft-auto-vice-city-ken-rosenberg-9961d42ce3e64c119d410ab6334912a5
Title: Grand Theft Auto Vice City - Ken Rosenberg
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function KenVice(props) {
  const { nodes, materials } = useGLTF('/kenVice-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Root.0']} />
    </group>
  )
}

useGLTF.preload('/kenVice-transformed.glb')
