/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 tommy.gltf --transform
Author: lechitachan (https://sketchfab.com/lechitachan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tommy-vercetti-a3f1b001135c4a0e8880c2227b54153d
Title: Tommy Vercetti
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tommy(props) {
  const { nodes, materials } = useGLTF('/tommy-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tommy_Vercetti_Mat_0.geometry} material={materials.material} />
    </group>
  )
}

useGLTF.preload('/tommy-transformed.glb')
